/** @type {import('tailwindcss').Config} */
export default {
  content: ["./index.html", "./src/**/*.{ts,tsx}"],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        background: "oklch(from var(--background) l c h / <alpha-value>)",
        "on-background": "oklch(from var(--on-background) l c h / <alpha-value>)",
        surface: "oklch(from var(--surface) l c h / <alpha-value>)",
        "surface-dim": "oklch(from var(--surface-dim) l c h / <alpha-value>)",
        "surface-bright": "oklch(from var(--surface-bright) l c h / <alpha-value>)",
        "surface-container-lowest": "oklch(from var(--surface-container-lowest) l c h / <alpha-value>)",
        "surface-container-low": "oklch(from var(--surface-container-low) l c h / <alpha-value>)",
        "surface-container": "oklch(from var(--surface-container) l c h / <alpha-value>)",
        "surface-container-high": "oklch(from var(--surface-container-high) l c h / <alpha-value>)",
        "surface-container-highest": "oklch(from var(--surface-container-highest) l c h / <alpha-value>)",
        "on-surface": "oklch(from var(--on-surface) l c h / <alpha-value>)",
        "on-surface-variant": "oklch(from var(--on-surface-variant) l c h / <alpha-value>)",
        "inverse-surface": "oklch(from var(--inverse-surface) l c h / <alpha-value>)",
        "inverse-on-surface": "oklch(from var(--inverse-on-surface) l c h / <alpha-value>)",
        outline: "oklch(from var(--outline) l c h / <alpha-value>)",
        "outline-variant": "oklch(from var(--outline-variant) l c h / <alpha-value>)",
        "surface-tint": "oklch(from var(--surface-tint) l c h / <alpha-value>)",
        "surface-variant": "oklch(from var(--surface-variant) l c h / <alpha-value>)",
        primary: "oklch(from var(--primary) l c h / <alpha-value>)",
        "on-primary": "oklch(from var(--on-primary) l c h / <alpha-value>)",
        "primary-container": "oklch(from var(--primary-container) l c h / <alpha-value>)",
        "on-primary-container": "oklch(from var(--on-primary-container) l c h / <alpha-value>)",
        "inverse-primary": "oklch(from var(--inverse-primary) l c h / <alpha-value>)",
        "primary-fixed": "oklch(from var(--primary-fixed) l c h / <alpha-value>)",
        "primary-fixed-dim": "oklch(from var(--primary-fixed-dim) l c h / <alpha-value>)",
        "on-primary-fixed": "oklch(from var(--on-primary-fixed) l c h / <alpha-value>)",
        "on-primary-fixed-variant": "oklch(from var(--on-primary-fixed-variant) l c h / <alpha-value>)",
        secondary: "oklch(from var(--secondary) l c h / <alpha-value>)",
        "on-secondary": "oklch(from var(--on-secondary) l c h / <alpha-value>)",
        "secondary-container": "oklch(from var(--secondary-container) l c h / <alpha-value>)",
        "on-secondary-container": "oklch(from var(--on-secondary-container) l c h / <alpha-value>)",
        "secondary-fixed": "oklch(from var(--secondary-fixed) l c h / <alpha-value>)",
        "secondary-fixed-dim": "oklch(from var(--secondary-fixed-dim) l c h / <alpha-value>)",
        "on-secondary-fixed": "oklch(from var(--on-secondary-fixed) l c h / <alpha-value>)",
        "on-secondary-fixed-variant": "oklch(from var(--on-secondary-fixed-variant) l c h / <alpha-value>)",
        tertiary: "oklch(from var(--tertiary) l c h / <alpha-value>)",
        "on-tertiary": "oklch(from var(--on-tertiary) l c h / <alpha-value>)",
        "tertiary-container": "oklch(from var(--tertiary-container) l c h / <alpha-value>)",
        "on-tertiary-container": "oklch(from var(--on-tertiary-container) l c h / <alpha-value>)",
        "tertiary-fixed": "oklch(from var(--tertiary-fixed) l c h / <alpha-value>)",
        "tertiary-fixed-dim": "oklch(from var(--tertiary-fixed-dim) l c h / <alpha-value>)",
        "on-tertiary-fixed": "oklch(from var(--on-tertiary-fixed) l c h / <alpha-value>)",
        "on-tertiary-fixed-variant": "oklch(from var(--on-tertiary-fixed-variant) l c h / <alpha-value>)",
        error: "oklch(from var(--error) l c h / <alpha-value>)",
        "on-error": "oklch(from var(--on-error) l c h / <alpha-value>)",
        "error-container": "oklch(from var(--error-container) l c h / <alpha-value>)",
        "on-error-container": "oklch(from var(--on-error-container) l c h / <alpha-value>)",
      },
      fontFamily: {
        "headline-lg": ["Hanken Grotesk", "sans-serif"],
        "headline-md": ["Hanken Grotesk", "sans-serif"],
        "headline-lg-mobile": ["Hanken Grotesk", "sans-serif"],
        "body-lg": ["Inter", "sans-serif"],
        "body-md": ["Inter", "sans-serif"],
        "label-md": ["Inter", "sans-serif"],
        "label-sm": ["Inter", "sans-serif"],
        sans: ["Inter", "sans-serif"],
      },
      fontSize: {
        "headline-lg": [
          "36px",
          { lineHeight: "1.2", letterSpacing: "-0.02em", fontWeight: "700" },
        ],
        "headline-lg-mobile": [
          "28px",
          { lineHeight: "1.2", fontWeight: "700" },
        ],
        "headline-md": [
          "24px",
          { lineHeight: "1.3", letterSpacing: "-0.01em", fontWeight: "600" },
        ],
        "body-lg": ["18px", { lineHeight: "1.6", fontWeight: "400" }],
        "body-md": ["16px", { lineHeight: "1.5", fontWeight: "400" }],
        "label-md": [
          "14px",
          { lineHeight: "1.2", letterSpacing: "0.05em", fontWeight: "600" },
        ],
        "label-sm": [
          "12px",
          { lineHeight: "1.2", fontWeight: "500" },
        ],
      },
      borderRadius: {
        DEFAULT: "0.25rem",
        lg: "0.5rem",
        xl: "0.75rem",
        full: "9999px",
      },
      spacing: {
        xs: "4px",
        sm: "8px",
        md: "16px",
        lg: "24px",
        xl: "40px",
        gutter: "24px",
        unit: "4px",
      },
    },
  },
  plugins: [],
};
